title: "Ionganic.Tee.Astute.Thought"
description: "Portal to RootRise / Astute Thought projects, briefs, and experiments"
theme: jekyll-theme-cayman
show_downloads: false
author: "Tee (Tamer Momtaz)"
